title: Binary hero
hero_image: images/banner.png
description: Score points by playing the notes of a song as they scroll past
listed: false
copyedit: true
version: 4.1.0
last_tested: 2018-11-02
steps: 
- title: Introduction
- title: Key presses
- title: Binary notes
- title: Play notes
- title: Scrolling notes
- title: Store your song
- title: More custom blocks
- title: Keep a score
- title: "Challenge: take it further"
  challenge: true
- title: "What next?"
